"use client"

import customTheme from "@/theme/theme";
import "./globals.css";
import { NextAuthProvider } from "./providers";
import { ChakraProvider } from '@chakra-ui/react'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={customTheme}>
          <NextAuthProvider>{children}</NextAuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
